services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: guarderia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  guarderia_api:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=guarderia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CORS_ORIGINS=["http://localhost:5173","http://localhost:3000"]
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
